name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: CompeyDev/setup-rokit@v0.1.2

    - name: Install binary dependencies
      run: rokit install --no-trust-check

    - name: Generate Standard Library
      run: selene generate-roblox-std

    - name: Run Selene
      run: selene .

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: CompeyDev/setup-rokit@v0.1.2

    - name: Install binary dependencies
      run: rokit install --no-trust-check

    - name: Run Stylua
      run: stylua --check --syntax luau --output-format Summary src